@startuml
package "RestaurantSim.SimulationSystem"{
    class FoodData
    class BuilderNotInitializedException
    interface IEvaluationService
    interface IOrderQualityDeterminer
    interface IOrderRater
    interface ITickableActionFinishCallback
    interface ITickableActionObject
    interface ITickableActionTickCallback
    class JsonDish
    class SimulationData
    class SimulationDataLoader
    class SimulationManager
    class SimulationSettings
    class SimulationSettingsLoader
    class SimulationUtilities
    class TickableAction
    class TickManager
    class PeopleData
}

package "RestaurantSim"{
    class Cook
    class CookBuilder
    class Customer
    class CustomerBuilder
    class Dish
    class Ingredient
    class Menu
    class Order
    class OrderReceipt
    class PreparedOrder
    enum PreparedOrderQuality
    class Program
    class QualityBasedOrderRater
    class RateBasedEvaluationService
    class Restaurant
    abstract class RestaurantGuest
    class Sanepid
    class SkillBasedQualityDeterminer

}


@enduml