


@startuml
title Creation of customer
start
#yellow:SimulationManager;
repeat
  :Generate TickableAction
  At finish -> spawn random Customer
  After = random amount of ticks between
  Settings.minTicksSpawnClient and Settings.maxTicksSpawnClient ;
  if (spawningCustomerAction.leftTicks <= 0) then
    :Create new customer;
    :Add customer to restaurant's queue;
  else
    :tick();
  endif
repeat while (restaurantOpen?) is (yes)
->no;
stop

@enduml

