
@startuml
title Ticking and Actions
start
#yellow:TickManager;
repeat
  :Tick;
  :For every registered tickableActionObject;
  :Decrement every tickable action left ticks;
  if (tickableAction duration == 0) then
    :Fire off tickableAction on finish callback;
    :Delete tickableAction from list of actions;
  endif
  if (tickableAction has on update callback) then
    :Fire off tickableAction on update callback;
  endif
  if(tickableActionObjectsBuffor is not empty) then
        :synchronize tickableActionObjectsBuffor;
  endif
  :cleanupTickableActionObjects;
  :printTickableActionsStatus;
  :increment passed ticks counter;
repeat while (simulationRunning?) is (yes)
->no;
stop
@enduml